"""Domain contracts for OMAS (Pydantic v2, extra=forbid, frozen)."""

from .artifact import Artifact, ArtifactKind
from .common import Epoch, Sha256Hex, UtcDatetime
from .decisions import (
    AwaitingEvent,
    AwaitingEventKind,
    Decision,
    DecisionAction,
    SlotOverride,
)
from .delivery import Delivery
from .errors import (
    ArtifactCorruptError,
    ArtifactExistsError,
    ArtifactHashMismatchError,
    ArtifactNotFoundError,
    CapabilityError,
    ConcurrencyError,
    IdempotencyConflictError,
    OmasError,
    PathEscapeError,
)
from .findings import CheckResult, GateName, GateReport, GateStatus, Severity
from .ids import (
    ArtifactId,
    AwaitingEventId,
    DecisionId,
    DeliveryId,
    NodeRunId,
    OperationId,
    SpanHandle,
    TaskId,
    TemplateVersionId,
    is_valid_id,
    new_artifact_id,
    new_awaiting_event_id,
    new_decision_id,
    new_delivery_id,
    new_id,
    new_node_run_id,
    new_operation_id,
    new_span_handle,
    new_task_id,
    new_template_version_id,
)
from .ir import (
    BindingIR,
    BoundBinding,
    ContentPlanIR,
    DocxRenderIR,
    InvalidBinding,
    MissingBinding,
    PlanSection,
    PlanSlot,
    Producer,
    RenderSlot,
    SlotBinding,
    SlotKind,
    TemplateStaticRef,
)
from .operations import IMPLEMENTATION_VERSION, Operation, OperationState
from .spans import SourceSpanRef
from .task import (
    TASK_STATUS_TRANSITIONS,
    TERMINAL_TASK_STATUSES,
    DataPolicy,
    NodeRun,
    NodeStatus,
    Task,
    TaskStatus,
)
from .template import (
    AnchorInfo,
    SlotSpec,
    StaticTextRegion,
    StyleSpec,
    TemplateContract,
    TemplatePackageHashes,
    UnsupportedFinding,
)

__all__ = [
    "IMPLEMENTATION_VERSION",
    "TASK_STATUS_TRANSITIONS",
    "TERMINAL_TASK_STATUSES",
    "AnchorInfo",
    "Artifact",
    "ArtifactCorruptError",
    "ArtifactExistsError",
    "ArtifactHashMismatchError",
    "ArtifactId",
    "ArtifactKind",
    "ArtifactNotFoundError",
    "AwaitingEvent",
    "AwaitingEventId",
    "AwaitingEventKind",
    "BindingIR",
    "BoundBinding",
    "CapabilityError",
    "CheckResult",
    "ConcurrencyError",
    "ContentPlanIR",
    "DataPolicy",
    "Decision",
    "DecisionAction",
    "DecisionId",
    "Delivery",
    "DeliveryId",
    "DocxRenderIR",
    "Epoch",
    "GateName",
    "GateReport",
    "GateStatus",
    "IdempotencyConflictError",
    "InvalidBinding",
    "MissingBinding",
    "NodeRun",
    "NodeRunId",
    "NodeStatus",
    "OmasError",
    "Operation",
    "OperationId",
    "OperationState",
    "PathEscapeError",
    "PlanSection",
    "PlanSlot",
    "Producer",
    "RenderSlot",
    "Severity",
    "Sha256Hex",
    "SlotBinding",
    "SlotKind",
    "SlotOverride",
    "SlotSpec",
    "SourceSpanRef",
    "SpanHandle",
    "StaticTextRegion",
    "StyleSpec",
    "Task",
    "TaskId",
    "TaskStatus",
    "TemplateContract",
    "TemplatePackageHashes",
    "TemplateStaticRef",
    "TemplateVersionId",
    "UnsupportedFinding",
    "UtcDatetime",
    "is_valid_id",
    "new_artifact_id",
    "new_awaiting_event_id",
    "new_decision_id",
    "new_delivery_id",
    "new_id",
    "new_node_run_id",
    "new_operation_id",
    "new_span_handle",
    "new_task_id",
    "new_template_version_id",
]
