"""Immutable artifact file pool under OMAS_HOME (P0, v1.1 §5 / §8.2).

Layout::

    OMAS_HOME/
        ledger.sqlite3                      (owned by the storage layer)
        runtime/                            runtime scratch (ingest staging)
        templates/<template_id>/<version>/
        tasks/<task_id>/
            inbox/  canonical/  projections/  deliverables/
            nodes/<run_id>/{work,out,logs}

Safety model (server-generated paths only):

- callers address artifacts exclusively by POSIX relative paths generated by
  this store; absolute paths are rejected
- lexical validation: no empty / ``.`` / ``..`` components, no backslash, no
  NUL byte, must not be absolute — re-checked after :func:`os.path.normpath`
- every existing ancestor below the root is ``lstat``-checked to not be a
  symlink (``PathEscapeError`` otherwise)
- reads open with ``O_NOFOLLOW`` so a symlink swapped in after validation
  fails closed (ELOOP → ``PathEscapeError``)
- writes create exclusively (``O_WRONLY | O_CREAT | O_EXCL``) and commit via
  :func:`os.replace` on the same filesystem (everything lives under OMAS_HOME),
  then fsync the file and its parent directory
- immutability: ``promote`` / ``adopt_existing`` / ``write_immutable`` never
  overwrite an existing file; new content requires a new path (a new artifact
  id).  The crash window between promotion and ledger registration is closed
  by ``adopt_existing`` (verify-by-hash, otherwise reject).

MVP assumption (v1.1 §5): OMAS_HOME is exclusive to the current user and a
single writer executor; this module defends against path mistakes and symlink
tricks, not against a hostile same-UID process racing it.
"""

from __future__ import annotations

import contextlib
import errno
import hashlib
import os
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path

from omas.domain.errors import (
    ArtifactExistsError,
    ArtifactHashMismatchError,
    ArtifactNotFoundError,
    PathEscapeError,
)

#: Size of read/hash chunks (files stay small; 1 MiB keeps memory bounded).
_CHUNK = 1024 * 1024

#: Fail closed on symlinked final components where the platform allows it.
_O_NOFOLLOW: int = getattr(os, "O_NOFOLLOW", 0)
_O_DIRECTORY: int = getattr(os, "O_DIRECTORY", 0)

_FORBIDDEN_COMPONENTS = frozenset({"", ".", ".."})


@dataclass(frozen=True, slots=True)
class StagedFile:
    """A file written under the store together with its computed digest.

    Produced by :meth:`ArtifactStore.stage` (run ``work/`` staging) and by
    :meth:`omas.artifacts.writers.InboxWriter.ingest_text`; in the latter case
    ``path`` already points at the final, immutable location.
    """

    #: Absolute location; internal use only — never hand this to callers.
    path: Path
    #: POSIX relative path under OMAS_HOME.
    relative_path: str
    #: Final path component (``<artifact_id>.txt`` for canonical text).
    name: str
    sha256: str
    size: int
    #: Code-point positions of characters forbidden in renderable text
    #: (populated by InboxWriter for canonical text). Never filtered
    #: silently — the caller decides whether to reject (v1.1 §3.2).
    illegal_positions: tuple[int, ...] = ()


@dataclass(frozen=True, slots=True)
class PromotedFile:
    """A file atomically committed to its final location in the pool."""

    relative_path: str
    sha256: str
    size: int


def _validated_parts(relative: str) -> tuple[str, ...]:
    """Validate a POSIX relative path and return its normalised components.

    Rejects absolute paths, backslashes, NUL bytes and empty / ``.`` / ``..``
    components, both lexically and after :func:`os.path.normpath`
    (defense in depth).
    """
    if not relative:
        raise PathEscapeError("relative path must be a non-empty POSIX relative path")
    if relative.startswith("/"):
        raise PathEscapeError(f"absolute paths are rejected: {relative!r}")
    if "\\" in relative:
        raise PathEscapeError(f"backslashes are rejected: {relative!r}")
    if "\x00" in relative:
        raise PathEscapeError("NUL byte in path")
    for component in relative.split("/"):
        if component in _FORBIDDEN_COMPONENTS:
            raise PathEscapeError(f"invalid path component {component!r} in {relative!r}")
    normalized = os.path.normpath(relative)
    if normalized.startswith("/") or normalized.split("/")[0] in ("", ".", ".."):
        raise PathEscapeError(f"path escapes the artifact root: {relative!r}")
    for component in normalized.split("/"):
        if component in _FORBIDDEN_COMPONENTS:
            raise PathEscapeError(f"invalid path component {component!r} in {relative!r}")
    return tuple(normalized.split("/"))


def _validated_component(value: str, what: str) -> str:
    """Validate a single path component (file name / id segment)."""
    if value in _FORBIDDEN_COMPONENTS or "/" in value or "\\" in value or "\x00" in value:
        raise PathEscapeError(f"invalid {what} component: {value!r}")
    return value


def _lstat_mode(path: Path) -> int | None:
    """``lstat`` mode of *path*, or ``None`` when it does not exist."""
    try:
        return os.lstat(path).st_mode
    except FileNotFoundError:
        return None


def _open_read(path: Path) -> int:
    """Open for reading without following a symlinked final component."""
    try:
        return os.open(path, os.O_RDONLY | _O_NOFOLLOW)
    except OSError as exc:
        if exc.errno == errno.ELOOP:
            raise PathEscapeError(f"refusing to read through a symlink: {path}") from exc
        if exc.errno == errno.ENOENT:
            raise ArtifactNotFoundError(f"artifact file not found: {path}") from exc
        raise


def _read_all(fd: int) -> bytes:
    chunks: list[bytes] = []
    while True:
        chunk = os.read(fd, _CHUNK)
        if not chunk:
            return b"".join(chunks)
        chunks.append(chunk)


def _hash_fd(fd: int) -> str:
    digest = hashlib.sha256()
    while True:
        chunk = os.read(fd, _CHUNK)
        if not chunk:
            return digest.hexdigest()
        digest.update(chunk)


def _write_all(fd: int, data: bytes) -> None:
    view = memoryview(data)
    while view:
        view = view[os.write(fd, view) :]


def _fsync_file(path: Path) -> None:
    fd = _open_read(path)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def _fsync_dir(path: Path) -> None:
    fd = os.open(path, os.O_RDONLY | _O_DIRECTORY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


class ArtifactStore:
    """The file pool: staging, atomic promotion, adoption and verified reads.

    All artifact paths are POSIX relative paths under OMAS_HOME and are
    generated by this class or by the capability writers; callers never pass
    absolute paths.
    """

    def __init__(self, root: Path) -> None:
        self._root = Path(os.path.abspath(os.path.expanduser(str(root))))
        self._root.mkdir(parents=True, exist_ok=True)
        for skeleton in ("runtime", "templates", "tasks"):
            self._ensure_dir(skeleton)

    @property
    def root(self) -> Path:
        """OMAS_HOME root — internal use (tests / diagnostics) only."""
        return self._root

    # —— path resolution and safety ————————————————————————————————————

    def resolve_path(self, relative: str) -> Path:
        """Resolve *relative* to an absolute path inside the pool.

        Rejects absolute paths, ``..`` / ``.`` / empty components, backslashes
        and NUL bytes (``PathEscapeError``); every existing ancestor below the
        root, including the target itself, must not be a symlink. The returned
        ``Path`` is for internal use only.
        """
        return self._resolve_checked(_validated_parts(relative))

    def _resolve_checked(self, parts: tuple[str, ...]) -> Path:
        current = self._root
        for part in parts:
            current = current / part
            mode = _lstat_mode(current)
            if mode is not None and stat.S_ISLNK(mode):
                raise PathEscapeError(f"path crosses a symlink: {current}")
        return current

    def _ensure_dir(self, relative: str) -> Path:
        """Create (or verify) the directory at *relative*, refusing symlinks."""
        current = self._root
        for part in _validated_parts(relative):
            current = current / part
            mode = _lstat_mode(current)
            if mode is None:
                try:
                    os.mkdir(current)
                    continue
                except FileExistsError:
                    mode = _lstat_mode(current)
                    if mode is None:  # pragma: no cover - pathological race
                        continue
            if stat.S_ISLNK(mode):
                raise PathEscapeError(f"path component is a symlink: {current}")
            if not stat.S_ISDIR(mode):
                raise NotADirectoryError(f"expected a directory: {current}")
        return current

    def _ensure_parent(self, parts: tuple[str, ...]) -> Path:
        if len(parts) < 2:
            return self._root
        return self._ensure_dir("/".join(parts[:-1]))

    # —— relative-path builders (all artifact paths are program-generated) —

    def inbox_relative(self, task_id: str, name: str) -> str:
        return (
            f"tasks/{_validated_component(task_id, 'task_id')}/inbox/"
            f"{_validated_component(name, 'inbox filename')}"
        )

    def canonical_relative(self, task_id: str, artifact_id: str) -> str:
        return (
            f"tasks/{_validated_component(task_id, 'task_id')}/canonical/"
            f"{_validated_component(artifact_id, 'artifact_id')}.txt"
        )

    def node_work_relative(self, task_id: str, run_id: str, name: str) -> str:
        return (
            f"tasks/{_validated_component(task_id, 'task_id')}/nodes/"
            f"{_validated_component(run_id, 'run_id')}/work/"
            f"{_validated_component(name, 'work filename')}"
        )

    def node_out_relative(self, task_id: str, run_id: str, name: str) -> str:
        return (
            f"tasks/{_validated_component(task_id, 'task_id')}/nodes/"
            f"{_validated_component(run_id, 'run_id')}/out/"
            f"{_validated_component(name, 'out filename')}"
        )

    def delivery_relative(self, task_id: str, name: str) -> str:
        return (
            f"tasks/{_validated_component(task_id, 'task_id')}/deliverables/"
            f"{_validated_component(name, 'delivery filename')}"
        )

    def template_relative(self, template_id: str, version: str, filename: str) -> str:
        return (
            f"templates/{_validated_component(template_id, 'template_id')}/"
            f"{_validated_component(version, 'template version')}/"
            f"{_validated_component(filename, 'template filename')}"
        )

    # —— directory skeleton ——————————————————————————————————————————————

    def task_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}")

    def inbox_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}/inbox")

    def canonical_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}/canonical")

    def nodes_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}/nodes")

    def run_dir(self, task_id: str, run_id: str) -> Path:
        task = _validated_component(task_id, "task_id")
        run = _validated_component(run_id, "run_id")
        for sub in ("work", "out", "logs"):
            self._ensure_dir(f"tasks/{task}/nodes/{run}/{sub}")
        return self._ensure_dir(f"tasks/{task}/nodes/{run}")

    def run_work_dir(self, task_id: str, run_id: str) -> Path:
        return self._ensure_dir(self.node_work_relative(task_id, run_id, "x").rsplit("/", 1)[0])

    def run_out_dir(self, task_id: str, run_id: str) -> Path:
        return self._ensure_dir(self.node_out_relative(task_id, run_id, "x").rsplit("/", 1)[0])

    def run_logs_dir(self, task_id: str, run_id: str) -> Path:
        return self._ensure_dir(
            f"tasks/{_validated_component(task_id, 'task_id')}/nodes/"
            f"{_validated_component(run_id, 'run_id')}/logs"
        )

    def projections_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}/projections")

    def deliverables_dir(self, task_id: str) -> Path:
        return self._ensure_dir(f"tasks/{_validated_component(task_id, 'task_id')}/deliverables")

    def template_dir(self, template_id: str, version: str) -> Path:
        return self._ensure_dir(
            f"templates/{_validated_component(template_id, 'template_id')}/"
            f"{_validated_component(version, 'template version')}"
        )

    # —— writing ————————————————————————————————————————————————————————

    def stage(self, task_id: str, run_id: str, name: str, data: bytes) -> StagedFile:
        """Write ``tasks/<task_id>/nodes/<run_id>/work/<name>`` and hash it.

        *name* follows the same rules as :meth:`resolve_path` components
        (single component). Creation is exclusive: an existing work file of
        the same name raises ``ArtifactExistsError`` (never overwrite).
        """
        relative = self.node_work_relative(task_id, run_id, name)
        target = self._resolve_checked(_validated_parts(relative))
        self._ensure_dir(relative.rsplit("/", 1)[0])
        try:
            fd = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL | _O_NOFOLLOW, 0o644)
        except FileExistsError as exc:
            raise ArtifactExistsError(f"staging target already exists: {target}") from exc
        try:
            _write_all(fd, data)
            os.fsync(fd)
        finally:
            os.close(fd)
        return StagedFile(
            path=target,
            relative_path=relative,
            name=relative.rsplit("/", 1)[1],
            sha256=hashlib.sha256(data).hexdigest(),
            size=len(data),
        )

    def promote(
        self,
        staged: StagedFile,
        final_relative: str,
        expected_sha256: str | None = None,
    ) -> PromotedFile:
        """Atomically lift *staged* to *final_relative* (never overwrite).

        TOCTOU protection: the staged file's hash is recomputed and compared
        against the staging digest (and against *expected_sha256* when given).
        The commit itself is :func:`os.replace` — same filesystem, since both
        staging and target live under OMAS_HOME — followed by fsync of the
        file and its parent directory. A crash after promotion but before
        ledger registration leaves an orphan recovered via
        :meth:`adopt_existing`.
        """
        parts = _validated_parts(final_relative)
        mode = _lstat_mode(staged.path)
        if mode is None:
            raise ArtifactNotFoundError(f"staged file no longer exists: {staged.path}")
        if stat.S_ISLNK(mode):
            raise PathEscapeError(f"staged path is a symlink: {staged.path}")

        fd = _open_read(staged.path)
        try:
            data = _read_all(fd)
            actual = hashlib.sha256(data).hexdigest()
        finally:
            os.close(fd)
        if actual != staged.sha256:
            raise ArtifactHashMismatchError(
                f"staged file changed since staging: {staged.path}"
            )
        if expected_sha256 is not None and actual != expected_sha256:
            raise ArtifactHashMismatchError(
                f"staged content does not match the expected sha256: {staged.path}"
            )

        parent = self._ensure_parent(parts)
        dest = parent / parts[-1]
        if os.path.lexists(dest):
            raise ArtifactExistsError(f"target already exists: {final_relative}")
        os.replace(staged.path, dest)
        _fsync_file(dest)
        _fsync_dir(parent)
        return PromotedFile(
            relative_path="/".join(parts), sha256=actual, size=len(data)
        )

    def write_immutable(self, final_relative: str, data: bytes) -> PromotedFile:
        """Crash-safely create a new immutable file at *final_relative*.

        Task-level staging variant used when no run ``work/`` directory is in
        play (ingest): the bytes are staged under ``runtime/staging/<random>``,
        fsynced, then atomically promoted with :func:`os.replace`. An existing
        target raises ``ArtifactExistsError`` — replay recovery goes through
        :meth:`adopt_existing`.
        """
        parts = _validated_parts(final_relative)
        parent = self._ensure_parent(parts)
        dest = parent / parts[-1]
        if os.path.lexists(dest):
            raise ArtifactExistsError(f"target already exists: {final_relative}")

        staging_root = self._ensure_dir("runtime/staging")
        tmp_dir = Path(tempfile.mkdtemp(dir=staging_root))
        try:
            tmp = tmp_dir / parts[-1]
            fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
            try:
                _write_all(fd, data)
                os.fsync(fd)
            finally:
                os.close(fd)
            if os.path.lexists(dest):
                raise ArtifactExistsError(f"target already exists: {final_relative}")
            os.replace(tmp, dest)
        finally:
            # Best effort cleanup of the (usually empty) staging directory;
            # leftovers belong to interrupted operations and are inert.
            with contextlib.suppress(OSError):
                tmp_dir.rmdir()
        _fsync_file(dest)
        _fsync_dir(parent)
        return PromotedFile(
            relative_path="/".join(parts),
            sha256=hashlib.sha256(data).hexdigest(),
            size=len(data),
        )

    def adopt_existing(self, final_relative: str, expected_sha256: str) -> PromotedFile:
        """Recover an orphan: verify an unregistered file against a hash.

        Crash window ``promotion done, registration not yet``: the caller
        supplies the expected digest (from the operation's manifest); a match
        returns the ``PromotedFile`` for registration, a mismatch raises
        ``ArtifactHashMismatchError`` ( unverifiable files are rejected, never
        blindly trusted by name — v1.1 §8.2), a missing file raises
        ``ArtifactNotFoundError``.
        """
        parts = _validated_parts(final_relative)
        path = self._resolve_checked(parts)
        fd = _open_read(path)  # ENOENT → ArtifactNotFoundError, ELOOP → PathEscapeError
        try:
            data = _read_all(fd)
        finally:
            os.close(fd)
        actual = hashlib.sha256(data).hexdigest()
        if actual != expected_sha256:
            raise ArtifactHashMismatchError(
                f"existing file does not match the expected sha256: {final_relative}"
            )
        return PromotedFile(relative_path="/".join(parts), sha256=actual, size=len(data))

    # —— reading ————————————————————————————————————————————————————————

    def read(self, relative: str) -> bytes:
        """Read raw bytes; opens with ``O_NOFOLLOW`` (symlinks fail closed).

        No hash check here — callers verify via :meth:`read_verified` /
        :meth:`verify` when a digest is known.
        """
        path = self.resolve_path(relative)
        fd = _open_read(path)
        try:
            return _read_all(fd)
        finally:
            os.close(fd)

    def read_verified(self, relative: str, expected_sha256: str) -> bytes:
        """Read and verify; mismatch raises ``ArtifactHashMismatchError``."""
        data = self.read(relative)
        if hashlib.sha256(data).hexdigest() != expected_sha256:
            raise ArtifactHashMismatchError(f"content hash mismatch: {relative}")
        return data

    def verify(self, relative: str, expected_sha256: str) -> None:
        """Streaming hash check; mismatch raises ``ArtifactHashMismatchError``."""
        path = self.resolve_path(relative)
        fd = _open_read(path)
        try:
            actual = _hash_fd(fd)
        finally:
            os.close(fd)
        if actual != expected_sha256:
            raise ArtifactHashMismatchError(f"content hash mismatch: {relative}")

    def exists(self, relative: str) -> bool:
        """Whether a regular file exists at *relative*.

        Symlinked ancestors or targets raise ``PathEscapeError`` (via
        :meth:`resolve_path`) rather than silently returning a boolean.
        """
        return os.path.isfile(self.resolve_path(relative))
